--[[
    init.lua
    Created: 08/24/2023 19:56:34
    Description: Autogenerated script file for the map end_treacherous_mountain.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local end_treacherous_mountain = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---end_treacherous_mountain.Init(map)
--Engine callback function
function end_treacherous_mountain.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---end_treacherous_mountain.Enter(map)
--Engine callback function
function end_treacherous_mountain.Enter(map)

  GAME:FadeIn(20)

end

---end_treacherous_mountain.Exit(map)
--Engine callback function
function end_treacherous_mountain.Exit(map)


end

---end_treacherous_mountain.Update(map)
--Engine callback function
function end_treacherous_mountain.Update(map)


end

---end_treacherous_mountain.GameSave(map)
--Engine callback function
function end_treacherous_mountain.GameSave(map)


end

---end_treacherous_mountain.GameLoad(map)
--Engine callback function
function end_treacherous_mountain.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return end_treacherous_mountain

