--[[
    init.lua
    Created: 08/24/2023 20:04:21
    Description: Autogenerated script file for the map end_ambush_forest.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local end_ambush_forest = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---end_ambush_forest.Init(map)
--Engine callback function
function end_ambush_forest.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---end_ambush_forest.Enter(map)
--Engine callback function
function end_ambush_forest.Enter(map)

  GAME:FadeIn(20)

end

---end_ambush_forest.Exit(map)
--Engine callback function
function end_ambush_forest.Exit(map)


end

---end_ambush_forest.Update(map)
--Engine callback function
function end_ambush_forest.Update(map)


end

---end_ambush_forest.GameSave(map)
--Engine callback function
function end_ambush_forest.GameSave(map)


end

---end_ambush_forest.GameLoad(map)
--Engine callback function
function end_ambush_forest.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return end_ambush_forest

